[package]
name = "keytray"
version = "0.0.0"
authors = ["Shota Nozaki <emonkak@gmail.com>"]
edition = "2018"

[features]
default = ["xlib"]
xlib = []

[dependencies]
libdbus-sys = "0.2.2"
nix = "0.23.1"
x11 = { version = "2.18.2", features = ["xft", "xinerama", "xlib"] }
