[window]
name = "test"
class = "test"
initial_width = 480.0
sticky = true

[ui]
container_padding = 8.0
item_padding = 8.0
item_gap = 8.0
icon_size = 24.0
item_corner_radius = 4.0
show_index = true
font_family = "Sans"
font_weight = 400
font_style = "Normal"
font_stretch = "Normal"
font_size = 12.0
window_background = "#21272b"
normal_item_background = "#363f45"
normal_item_foreground = "#e8eaeb"
selected_item_background = "#1c95e6"
selected_item_foreground = "#e8eaeb"

[[hotkeys]]
keysym = "1"
commands = [ { type = "SelectItem", params = 0 } ]

[[hotkeys]]
keysym = "2"
commands = [ { type = "SelectItem", params = 1 } ]

[[hotkeys]]
keysym = "3"
commands = [ { type = "SelectItem", params = 2 } ]

[[hotkeys]]
keysym = "4"
commands = [ { type = "SelectItem", params = 3 } ]

[[hotkeys]]
keysym = "5"
commands = [ { type = "SelectItem", params = 4 } ]

[[hotkeys]]
keysym = "6"
commands = [ { type = "SelectItem", params = 5 } ]

[[hotkeys]]
keysym = "7"
commands = [ { type = "SelectItem", params = 6 } ]

[[hotkeys]]
keysym = "8"
commands = [ { type = "SelectItem", params = 7 } ]

[[hotkeys]]
keysym = "9"
commands = [ { type = "SelectItem", params = 8 } ]

[[hotkeys]]
keysym = "j"
commands = [ { type = "SelectNextItem" } ]

[[hotkeys]]
keysym = "Down"
commands = [ { type = "SelectNextItem" } ]

[[hotkeys]]
keysym = "n"
modifiers = { control = true }
commands = [ { type = "SelectNextItem" } ]

[[hotkeys]]
keysym = "k"
commands = [ { type = "SelectPreviousItem" } ]

[[hotkeys]]
keysym = "Up"
commands = [ { type = "SelectPreviousItem" } ]

[[hotkeys]]
keysym = "p"
modifiers = { control = true }
commands = [ { type = "SelectPreviousItem" } ]

[[hotkeys]]
keysym = "l"
commands = [ { type = "ClickMouseButton", params = "Left" } ]

[[hotkeys]]
keysym = "Return"
commands = [ { type = "ClickMouseButton", params = "Left" } ]

[[hotkeys]]
keysym = "h"
commands = [ { type = "ClickMouseButton", params = "Right" } ]

[[hotkeys]]
keysym = "Return"
modifiers = { shift = true }
commands = [ { type = "ClickMouseButton", params = "Left" } ]

[[hotkeys]]
keysym = "q"
commands = [ { type = "HideWindow" } ]

[[hotkeys]]
keysym = "Escape"
commands = [ { type = "HideWindow" } ]

[[global_hotkeys]]
keysym = "grave"
modifiers = { super = true }
commands = [ { type = "ToggleWindow" } ]
