name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update packages
      run: sudo apt-get update
    - name: Install packages
      run: sudo apt-get -y install libcairo2 libglib2.0 libpango1.0 libxkbcommon-x11-dev
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
